service: my-app
image: huacheng23/my-app

servers:
  web:
    - 5.161.121.234

volumes:
  # host path:container path
  - "/db:/rails/sqlite"
  - "/storage:/rails/storage"

registry:
  username: huacheng23
  password:
    - KAMAL_REGISTRY_PASSWORD

builder:
  arch: amd64

env:
  secret:
    - RAILS_MASTER_KEY
